-- Generated by scripts/generate-sql-migration.sh
-- Description: baseline_schema
-- Generated at: 2026-10-03T12:29:00Z
-- Apply this file to an empty database before starting the backend.
-- Server startup still validates the schema and records the migration
-- ledger; it never adds columns or tables outside that contract.

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `audit_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `action` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `resource_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT '0',
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_logs_user_id` (`user_id`),
  KEY `idx_audit_logs_action` (`action`),
  CONSTRAINT `fk_audit_logs_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `csrf_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `session_id` bigint unsigned NOT NULL,
  `token_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expires_at` datetime(3) NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_csrf_tokens_token_hash` (`token_hash`),
  KEY `idx_csrf_tokens_session_id` (`session_id`),
  CONSTRAINT `fk_csrf_tokens_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image_access_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `image_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expires_at` datetime(3) NOT NULL,
  `revoked_at` datetime(3) DEFAULT NULL,
  `usage_count` bigint unsigned NOT NULL DEFAULT '0',
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_image_access_tokens_token` (`token`),
  KEY `idx_image_access_tokens_user_id` (`user_id`),
  KEY `idx_image_access_tokens_revoked_at` (`revoked_at`),
  KEY `idx_image_access_tokens_image_id` (`image_id`),
  CONSTRAINT `fk_image_access_tokens_image` FOREIGN KEY (`image_id`) REFERENCES `images` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_image_access_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image_files` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `file_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_size` bigint NOT NULL,
  `mime_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `width` bigint DEFAULT '0',
  `height` bigint DEFAULT '0',
  `reference_count` bigint NOT NULL DEFAULT '1',
  `original_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `thumbnail_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `processed_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remote_backend` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `remote_endpoint` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `remote_bucket` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_image_files_file_hash` (`file_hash`),
  KEY `idx_image_files_original_path` (`original_path`),
  KEY `idx_image_files_thumbnail_path` (`thumbnail_path`),
  KEY `idx_image_files_processed_path` (`processed_path`),
  KEY `idx_image_files_remote_backend` (`remote_backend`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image_variants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `image_id` bigint unsigned NOT NULL,
  `kind` varchar(24) NOT NULL,
  `revision` int unsigned NOT NULL DEFAULT '1',
  `pipeline_version` smallint unsigned NOT NULL DEFAULT '2',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `file_hash` varchar(64) NOT NULL,
  `file_size` bigint NOT NULL,
  `mime_type` varchar(50) NOT NULL,
  `width` bigint NOT NULL,
  `height` bigint NOT NULL,
  `quality` tinyint unsigned NOT NULL DEFAULT '0',
  `storage_path` varchar(500) NOT NULL,
  `watermark_version` varchar(64) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `ready_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_image_variant_revision` (`image_id`,`kind`,`revision`),
  KEY `idx_image_variants_image_id` (`image_id`),
  KEY `idx_image_variants_kind` (`kind`),
  KEY `idx_image_variants_status` (`status`),
  KEY `idx_image_variants_file_hash` (`file_hash`),
  KEY `idx_image_variants_watermark_version` (`watermark_version`),
  KEY `idx_image_variants_is_active` (`is_active`),
  KEY `idx_image_variants_ready_at` (`ready_at`),
  KEY `idx_image_variants_storage_path` (`storage_path`),
  CONSTRAINT `fk_image_variants_image` FOREIGN KEY (`image_id`) REFERENCES `images` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `images` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `image_file_id` bigint unsigned NOT NULL,
  `unique_link` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `filename` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visibility` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'public',
  `pipeline_version` smallint unsigned NOT NULL DEFAULT '1',
  `processing_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'completed',
  `origin_alias` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `view_count` bigint unsigned NOT NULL DEFAULT '0',
  `width` bigint DEFAULT '0',
  `height` bigint DEFAULT '0',
  `file_size` bigint NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_images_unique_link` (`unique_link`),
  KEY `idx_images_image_file_id` (`image_file_id`),
  KEY `idx_images_user_id` (`user_id`),
  KEY `idx_images_processing_status` (`processing_status`),
  KEY `idx_images_origin_alias` (`origin_alias`),
  CONSTRAINT `fk_images_image_file` FOREIGN KEY (`image_file_id`) REFERENCES `image_files` (`id`),
  CONSTRAINT `fk_images_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notifications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci,
  `is_read` tinyint(1) NOT NULL DEFAULT '0',
  `metadata` json DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_user_id` (`user_id`),
  KEY `idx_notifications_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `outbox_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `aggregate_type` varchar(50) NOT NULL,
  `aggregate_id` varchar(64) NOT NULL,
  `event_type` varchar(100) NOT NULL,
  `dedupe_key` varchar(128) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `payload` json NOT NULL,
  `attempts` bigint unsigned NOT NULL DEFAULT '0',
  `max_attempts` bigint unsigned NOT NULL DEFAULT '10',
  `available_at` datetime(3) NOT NULL,
  `lease_owner` varchar(100) DEFAULT NULL,
  `lease_token` varchar(64) DEFAULT NULL,
  `lease_expires_at` datetime(3) DEFAULT NULL,
  `published_at` datetime(3) DEFAULT NULL,
  `last_error` text,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_outbox_event_dedupe` (`event_type`,`dedupe_key`),
  KEY `idx_outbox_events_aggregate_type` (`aggregate_type`),
  KEY `idx_outbox_events_aggregate_id` (`aggregate_id`),
  KEY `idx_outbox_events_event_type` (`event_type`),
  KEY `idx_outbox_event_claim` (`status`,`available_at`),
  KEY `idx_outbox_events_lease_owner` (`lease_owner`),
  KEY `idx_outbox_events_lease_token` (`lease_token`),
  KEY `idx_outbox_events_lease_expires_at` (`lease_expires_at`),
  KEY `idx_outbox_events_published_at` (`published_at`),
  KEY `idx_outbox_events_retention` (`status`,`published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `processing_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `job_type` varchar(50) NOT NULL,
  `dedupe_key` varchar(128) NOT NULL,
  `image_id` bigint unsigned DEFAULT NULL,
  `upload_session_id` bigint unsigned DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'queued',
  `priority` bigint NOT NULL DEFAULT '0',
  `payload` json NOT NULL,
  `attempts` bigint unsigned NOT NULL DEFAULT '0',
  `max_attempts` bigint unsigned NOT NULL DEFAULT '5',
  `available_at` datetime(3) NOT NULL,
  `lease_owner` varchar(100) DEFAULT NULL,
  `lease_token` varchar(64) DEFAULT NULL,
  `lease_expires_at` datetime(3) DEFAULT NULL,
  `started_at` datetime(3) DEFAULT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `last_error` text,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_processing_job_dedupe` (`job_type`,`dedupe_key`),
  KEY `idx_processing_jobs_job_type` (`job_type`),
  KEY `idx_processing_jobs_image_id` (`image_id`),
  KEY `idx_processing_jobs_upload_session_id` (`upload_session_id`),
  KEY `idx_processing_job_claim` (`status`,`available_at`,`priority`),
  KEY `idx_processing_jobs_lease_owner` (`lease_owner`),
  KEY `idx_processing_jobs_lease_token` (`lease_token`),
  KEY `idx_processing_jobs_lease_expires_at` (`lease_expires_at`),
  KEY `idx_processing_jobs_retention` (`status`,`updated_at`),
  CONSTRAINT `fk_processing_jobs_image` FOREIGN KEY (`image_id`) REFERENCES `images` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_processing_jobs_upload_session` FOREIGN KEY (`upload_session_id`) REFERENCES `upload_sessions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `schema_migrations` (
  `version` bigint unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `checksum` char(64) NOT NULL,
  `applied_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `token_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token_type` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `identity_token_id` bigint unsigned DEFAULT NULL,
  `nonce_hash` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_heartbeat_at` datetime(3) DEFAULT NULL,
  `heartbeat_grace_seconds` bigint unsigned NOT NULL DEFAULT '600',
  `device_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `platform` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'web',
  `device_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `last_active_at` datetime(3) DEFAULT NULL,
  `expires_at` datetime(3) NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_sessions_token_hash` (`token_hash`),
  KEY `idx_sessions_token_type` (`token_type`),
  KEY `idx_sessions_identity_token_id` (`identity_token_id`),
  KEY `idx_sessions_platform` (`platform`),
  KEY `idx_sessions_last_active_at` (`last_active_at`),
  KEY `idx_sessions_user_id` (`user_id`),
  KEY `idx_sessions_last_heartbeat_at` (`last_heartbeat_at`),
  KEY `idx_sessions_device_id` (`device_id`),
  KEY `idx_sessions_expires_at` (`expires_at`),
  CONSTRAINT `fk_sessions_identity_token` FOREIGN KEY (`identity_token_id`) REFERENCES `sessions` (`id`),
  CONSTRAINT `fk_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `system_configs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `config_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `config_value` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `config_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_system_configs_config_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `upload_parts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `upload_session_id` bigint unsigned NOT NULL,
  `kind` varchar(24) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `expected_size` bigint NOT NULL DEFAULT '0',
  `actual_size` bigint NOT NULL DEFAULT '0',
  `expected_hash` varchar(64) DEFAULT NULL,
  `actual_hash` varchar(64) DEFAULT NULL,
  `expected_width` bigint NOT NULL DEFAULT '0',
  `expected_height` bigint NOT NULL DEFAULT '0',
  `actual_width` bigint NOT NULL DEFAULT '0',
  `actual_height` bigint NOT NULL DEFAULT '0',
  `expected_mime_type` varchar(50) DEFAULT NULL,
  `actual_mime_type` varchar(50) DEFAULT NULL,
  `staging_path` varchar(500) NOT NULL,
  `final_path` varchar(500) DEFAULT NULL,
  `received_at` datetime(3) DEFAULT NULL,
  `finalized_at` datetime(3) DEFAULT NULL,
  `cleaned_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_upload_part_kind` (`upload_session_id`,`kind`),
  KEY `idx_upload_parts_upload_session_id` (`upload_session_id`),
  KEY `idx_upload_parts_status` (`status`),
  KEY `idx_upload_parts_actual_hash` (`actual_hash`),
  CONSTRAINT `fk_upload_parts_upload_session` FOREIGN KEY (`upload_session_id`) REFERENCES `upload_sessions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `upload_queues` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'processing',
  `total_count` bigint NOT NULL DEFAULT '0',
  `processed_count` bigint NOT NULL DEFAULT '0',
  `file_info` json DEFAULT NULL,
  `error_message` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_upload_queues_user_id` (`user_id`),
  KEY `idx_upload_queues_status` (`status`),
  CONSTRAINT `fk_upload_queues_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `upload_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `upload_key` varchar(64) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `idempotency_key` varchar(64) DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'initiated',
  `pipeline_version` smallint unsigned NOT NULL DEFAULT '2',
  `visibility` varchar(10) NOT NULL DEFAULT 'public',
  `filename` varchar(255) NOT NULL,
  `source_mime_type` varchar(50) NOT NULL,
  `source_width` bigint NOT NULL DEFAULT '0',
  `source_height` bigint NOT NULL DEFAULT '0',
  `processor_version` varchar(64) NOT NULL,
  `recipe_version` varchar(32) NOT NULL,
  `image_id` bigint unsigned DEFAULT NULL,
  `expected_part_count` tinyint unsigned NOT NULL DEFAULT '0',
  `received_part_count` tinyint unsigned NOT NULL DEFAULT '0',
  `reserved_bytes` bigint NOT NULL DEFAULT '0',
  `actual_bytes` bigint NOT NULL DEFAULT '0',
  `staging_path` varchar(500) NOT NULL,
  `manifest_hash` varchar(64) DEFAULT NULL,
  `client_manifest` json DEFAULT NULL,
  `focal_x` decimal(8,7) DEFAULT NULL,
  `focal_y` decimal(8,7) DEFAULT NULL,
  `error_code` bigint DEFAULT NULL,
  `error_message` text,
  `expires_at` datetime(3) NOT NULL,
  `processing_at` datetime(3) DEFAULT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `failed_at` datetime(3) DEFAULT NULL,
  `cancelled_at` datetime(3) DEFAULT NULL,
  `cleanup_after` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_upload_sessions_upload_key` (`upload_key`),
  UNIQUE KEY `uk_user_upload_idempotency` (`user_id`,`idempotency_key`),
  KEY `idx_upload_sessions_user_id` (`user_id`),
  KEY `idx_upload_sessions_image_id` (`image_id`),
  KEY `idx_upload_session_expiry` (`status`,`expires_at`),
  KEY `idx_upload_sessions_cleanup_after` (`cleanup_after`),
  KEY `idx_upload_sessions_user_status` (`user_id`,`status`,`expires_at`),
  KEY `idx_upload_sessions_retention` (`status`,`updated_at`),
  CONSTRAINT `fk_upload_sessions_image` FOREIGN KEY (`image_id`) REFERENCES `images` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_upload_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'user',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `avatar_url` mediumtext COLLATE utf8mb4_unicode_ci,
  `storage_used` bigint NOT NULL DEFAULT '0',
  `storage_quota` bigint NOT NULL DEFAULT '524288000',
  `image_count` bigint NOT NULL DEFAULT '0',
  `deletion_scheduled_at` datetime(3) DEFAULT NULL,
  `deleted_by_admin` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `batch_download_count` bigint NOT NULL DEFAULT '0',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_users_username` (`username`),
  UNIQUE KEY `idx_users_email` (`email`),
  KEY `idx_users_deletion_scheduled_at` (`deletion_scheduled_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `v2_capacity_locks` (
  `id` tinyint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS=1;
