#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
backend_dir="${repo_root}/backend"
dsn="${SUMMERAIN_SCHEMA_DSN:-root:summerain-dev@tcp(127.0.0.1:13306)/?charset=utf8mb4&parseTime=True&loc=Local}"

usage() {
  cat >&2 <<'EOF'
usage: scripts/generate-sql-migration.sh <description>
       scripts/generate-sql-migration.sh --verify <file>

Renders the MySQL schema that matches the GORM models plus the checksummed
migrations. With a description it writes
backend/migrations/<UTC timestamp>_<description>.up.sql and verifies the file.
With --verify it re-checks an existing file only.

SUMMERAIN_SCHEMA_DSN selects the MySQL server (default: the dev-deps server
started by ./scripts/dev-wsl.sh deps-up). The tool creates and drops its own
disposable databases and never touches an existing one.
EOF
}

generate() {
  local description="$1"
  if [[ ! "$description" =~ ^[a-z0-9_]+$ ]]; then
    echo "description must match ^[a-z0-9_]+$" >&2
    exit 2
  fi
  local stamp timestamp target
  stamp="$(date -u +%Y%m%d_%H%M%S)"
  timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  target="${backend_dir}/migrations/${stamp}_${description}.up.sql"

  {
    echo "-- Generated by scripts/generate-sql-migration.sh"
    echo "-- Description: ${description}"
    echo "-- Generated at: ${timestamp}"
    echo "-- Apply this file to an empty database before starting the backend."
    echo "-- Server startup still validates the schema and records the migration"
    echo "-- ledger; it never adds columns or tables outside that contract."
    echo
    (cd "${backend_dir}" && SUMMERAIN_SCHEMA_DSN="${dsn}" go run ./cmd/schema-migration-gen dump)
  } > "${target}"

  echo "wrote ${target#"${repo_root}/"}"
  SUMMERAIN_SCHEMA_DSN="${dsn}" bash "$0" --verify "${target}"
}

case "${1:-}" in
  "" | -h | --help)
    usage
    exit 2
    ;;
  --verify)
    if [[ $# -ne 2 ]]; then
      usage
      exit 2
    fi
    # Resolve before changing directory so a repo-root-relative path works as documented.
    if [[ ! -f "$2" ]]; then
      echo "migration file not found: $2" >&2
      exit 2
    fi
    target="$(realpath "$2")"
    (cd "${backend_dir}" && SUMMERAIN_SCHEMA_DSN="${dsn}" go run ./cmd/schema-migration-gen verify "${target}")
    ;;
  *)
    generate "$1"
    ;;
esac
